export const AchievementDatabase = [
  // --- Combat Achievements ---
  {
    id: "ach_first_blood",
    name: "First Blood",
    desc: "Defeat your first enemy.",
    icon: "⚔️",
    category: "combat",
    reward: { coins: 500 },
    condition: (stats) => stats.enemiesDefeated >= 1,
  },
  {
    id: "ach_slayer_100",
    name: "Exterminator",
    desc: "Defeat 100 enemies.",
    icon: "💀",
    category: "combat",
    reward: { coins: 1000 },
    condition: (stats) => stats.enemiesDefeated >= 100,
  },
  {
    id: "ach_slayer_1000",
    name: "Annihilator",
    desc: "Defeat 1,000 enemies.",
    icon: "☠️",
    category: "combat",
    reward: { coins: 5000, stardust: 10 },
    condition: (stats) => stats.enemiesDefeated >= 1000,
  },
  {
    id: "ach_slayer_10000",
    name: "Apocalyptic",
    desc: "Defeat 10,000 enemies.",
    icon: "🔥",
    category: "combat",
    reward: { coins: 25000, gems: 5 },
    condition: (stats) => stats.enemiesDefeated >= 10000,
  },
  {
    id: "ach_slayer_50000",
    name: "Extinction Event",
    desc: "Defeat 50,000 enemies.",
    icon: "🌑",
    category: "combat",
    reward: { coins: 100000, gems: 15, stardust: 50 },
    condition: (stats) => stats.enemiesDefeated >= 50000,
  },
  {
    id: "ach_boss_hunter",
    name: "Boss Hunter",
    desc: "Defeat 10 bosses.",
    icon: "👑",
    category: "combat",
    reward: { coins: 2000, stardust: 5 },
    condition: (stats) => stats.bossesDefeated >= 10,
  },
  {
    id: "ach_boss_slayer",
    name: "Boss Slayer",
    desc: "Defeat 50 bosses.",
    icon: "🐉",
    category: "combat",
    reward: { coins: 5000, stardust: 15 },
    condition: (stats) => stats.bossesDefeated >= 50,
  },
  {
    id: "ach_boss_master",
    name: "Boss Vanquisher",
    desc: "Defeat 200 bosses.",
    icon: "🏴",
    category: "combat",
    reward: { coins: 25000, gems: 5 },
    condition: (stats) => stats.bossesDefeated >= 200,
  },
  {
    id: "ach_click_100",
    name: "Clicker Novice",
    desc: "Click 100 times.",
    icon: "👆",
    category: "combat",
    reward: { coins: 500 },
    condition: (stats) => stats.totalClicks >= 100,
  },
  {
    id: "ach_click_1000",
    name: "Rapid Tapper",
    desc: "Click 1,000 times.",
    icon: "👇",
    category: "combat",
    reward: { coins: 2500 },
    condition: (stats) => stats.totalClicks >= 1000,
  },
  {
    id: "ach_click_10000",
    name: "Carpal Tunnel",
    desc: "Click 10,000 times.",
    icon: "🖱️",
    category: "combat",
    reward: { coins: 10000 },
    condition: (stats) => stats.totalClicks >= 10000,
  },
  {
    id: "ach_click_50000",
    name: "Legendary Fingers",
    desc: "Click 50,000 times.",
    icon: "✋",
    category: "combat",
    reward: { coins: 50000 },
    condition: (stats) => stats.totalClicks >= 50000,
  },
  {
    id: "ach_crit_50",
    name: "Lucky Strike",
    desc: "Land 50 critical hits.",
    icon: "💥",
    category: "combat",
    reward: { coins: 1000, stardust: 5 },
    condition: (stats) => stats.criticalHits >= 50,
  },
  {
    id: "ach_crit_500",
    name: "Critical Mass",
    desc: "Land 500 critical hits.",
    icon: "⚡",
    category: "combat",
    reward: { coins: 5000, stardust: 15 },
    condition: (stats) => stats.criticalHits >= 500,
  },
  {
    id: "ach_crit_5000",
    name: "Precision Master",
    desc: "Land 5,000 critical hits.",
    icon: "🎯",
    category: "combat",
    reward: { coins: 25000, stardust: 30 },
    condition: (stats) => stats.criticalHits >= 5000,
  },
  {
    id: "ach_dmg_million",
    name: "Million Damage Club",
    desc: "Deal 1,000,000 total damage.",
    icon: "💣",
    category: "combat",
    reward: { coins: 5000, gems: 2 },
    condition: (stats) => stats.totalDamageDealt >= 1000000,
  },
  {
    id: "ach_dmg_billion",
    name: "Billion Damage Club",
    desc: "Deal 1,000,000,000 total damage.",
    icon: "🌋",
    category: "combat",
    reward: { coins: 25000, gems: 10 },
    condition: (stats) => stats.totalDamageDealt >= 1000000000,
  },
  {
    id: "ach_dmg_trillion",
    name: "Trillion Damage Club",
    desc: "Deal 1,000,000,000,000 total damage.",
    icon: "☄️",
    category: "combat",
    reward: { coins: 100000, gems: 25 },
    condition: (stats) => stats.totalDamageDealt >= 1000000000000,
  },

  // --- Progression Achievements ---
  {
    id: "ach_stage_10",
    name: "Getting Started",
    desc: "Reach Stage 10.",
    icon: "🌱",
    category: "progression",
    reward: { coins: 1000 },
    condition: (stats) => stats.highestStage >= 10,
  },
  {
    id: "ach_stage_25",
    name: "On the Road",
    desc: "Reach Stage 25.",
    icon: "🚶",
    category: "progression",
    reward: { coins: 2500, stardust: 5 },
    condition: (stats) => stats.highestStage >= 25,
  },
  {
    id: "ach_stage_50",
    name: "Adventurer",
    desc: "Reach Stage 50.",
    icon: "🗺️",
    category: "progression",
    reward: { coins: 5000, stardust: 10 },
    condition: (stats) => stats.highestStage >= 50,
  },
  {
    id: "ach_stage_100",
    name: "Veteran",
    desc: "Reach Stage 100.",
    icon: "🏅",
    category: "progression",
    reward: { coins: 10000, stardust: 15, gems: 2 },
    condition: (stats) => stats.highestStage >= 100,
  },
  {
    id: "ach_stage_250",
    name: "Legend",
    desc: "Reach Stage 250.",
    icon: "🏆",
    category: "progression",
    reward: { coins: 25000, stardust: 25, gems: 5 },
    condition: (stats) => stats.highestStage >= 250,
  },
  {
    id: "ach_stage_500",
    name: "Mythical",
    desc: "Reach Stage 500.",
    icon: "⭐",
    category: "progression",
    reward: { coins: 50000, stardust: 35, gems: 10 },
    condition: (stats) => stats.highestStage >= 500,
  },
  {
    id: "ach_stage_1000",
    name: "Transcendent",
    desc: "Reach Stage 1,000.",
    icon: "🌌",
    category: "progression",
    reward: { coins: 100000, stardust: 50, gems: 15 },
    condition: (stats) => stats.highestStage >= 1000,
  },
  {
    id: "ach_tower_3",
    name: "Tower Climber",
    desc: "Clear Eclipse Tower Floor 3.",
    icon: "🏰",
    category: "progression",
    reward: { stardust: 10, gems: 1 },
    condition: (stats) => stats.highestTowerFloor > 3,
  },
  {
    id: "ach_tower_6",
    name: "Tower Warrior",
    desc: "Clear Eclipse Tower Floor 6.",
    icon: "🗡️",
    category: "progression",
    reward: { stardust: 25, gems: 3 },
    condition: (stats) => stats.highestTowerFloor > 6,
  },
  {
    id: "ach_tower_8",
    name: "Tower Master",
    desc: "Clear Eclipse Tower Floor 8.",
    icon: "🗼",
    category: "progression",
    reward: { stardust: 40, gems: 5 },
    condition: (stats) => stats.highestTowerFloor > 8,
  },
  {
    id: "ach_tower_12",
    name: "Ascended",
    desc: "Clear all Eclipse Tower Floors.",
    icon: "🌠",
    category: "progression",
    reward: { stardust: 75, gems: 10 },
    condition: (stats) => stats.highestTowerFloor > 12,
  },

  // --- Economy Achievements ---
  {
    id: "ach_coins_10k",
    name: "Prospector",
    desc: "Earn 10,000 coins total.",
    icon: "🪙",
    category: "economy",
    reward: { stardust: 5 },
    condition: (stats) => stats.totalCoinsEarned >= 10000,
  },
  {
    id: "ach_coins_100k",
    name: "Merchant",
    desc: "Earn 100,000 coins total.",
    icon: "💵",
    category: "economy",
    reward: { stardust: 15 },
    condition: (stats) => stats.totalCoinsEarned >= 100000,
  },
  {
    id: "ach_coins_1m",
    name: "Tycoon",
    desc: "Earn 1,000,000 coins total.",
    icon: "💰",
    category: "economy",
    reward: { stardust: 30 },
    condition: (stats) => stats.totalCoinsEarned >= 1000000,
  },
  {
    id: "ach_coins_100m",
    name: "Billionaire",
    desc: "Earn 100,000,000 coins total.",
    icon: "🏦",
    category: "economy",
    reward: { stardust: 50, gems: 5 },
    condition: (stats) => stats.totalCoinsEarned >= 100000000,
  },
  {
    id: "ach_stardust_100",
    name: "Stargazer",
    desc: "Earn 100 Stardust total.",
    icon: "✨",
    category: "economy",
    reward: { gems: 2 },
    condition: (stats) => stats.totalStardustEarned >= 100,
  },
  {
    id: "ach_stardust_1k",
    name: "Star Farmer",
    desc: "Earn 1,000 Stardust total.",
    icon: "🌠",
    category: "economy",
    reward: { gems: 5 },
    condition: (stats) => stats.totalStardustEarned >= 1000,
  },
  {
    id: "ach_stardust_10k",
    name: "Celestial Collector",
    desc: "Earn 10,000 Stardust total.",
    icon: "🌟",
    category: "economy",
    reward: { gems: 15 },
    condition: (stats) => stats.totalStardustEarned >= 10000,
  },
  {
    id: "ach_gems_10",
    name: "Gem Finder",
    desc: "Earn 10 Gems total.",
    icon: "💎",
    category: "economy",
    reward: { essence: 2 },
    condition: (stats) => (stats.totalGemsEarned || 0) >= 10,
  },
  {
    id: "ach_gems_100",
    name: "Jeweler",
    desc: "Earn 100 Gems total.",
    icon: "💠",
    category: "economy",
    reward: { essence: 5 },
    condition: (stats) => (stats.totalGemsEarned || 0) >= 100,
  },
  {
    id: "ach_gems_1000",
    name: "Diamond Mogul",
    desc: "Earn 1,000 Gems total.",
    icon: "👑",
    category: "economy",
    reward: { essence: 15 },
    condition: (stats) => (stats.totalGemsEarned || 0) >= 1000,
  },
  {
    id: "ach_essence_10",
    name: "Void Touched",
    desc: "Earn 10 Essence total.",
    icon: "🌀",
    category: "economy",
    reward: { coins: 50000, stardust: 25 },
    condition: (stats) => (stats.totalEssenceEarned || 0) >= 10,
  },
  {
    id: "ach_essence_100",
    name: "Void Walker",
    desc: "Earn 100 Essence total.",
    icon: "🔮",
    category: "economy",
    reward: { coins: 100000, stardust: 50, gems: 10 },
    condition: (stats) => (stats.totalEssenceEarned || 0) >= 100,
  },

  // --- Collection Achievements ---
  {
    id: "ach_hero_1",
    name: "First Recruit",
    desc: "Recruit your first hero.",
    icon: "🙋",
    category: "collection",
    reward: { coins: 500, stardust: 3 },
    condition: (stats) => stats.heroesRecruited >= 1,
  },
  {
    id: "ach_hero_5",
    name: "Band of Five",
    desc: "Recruit 5 heroes.",
    icon: "🤝",
    category: "collection",
    reward: { coins: 1000, stardust: 5 },
    condition: (stats) => stats.heroesRecruited >= 5,
  },
  {
    id: "ach_hero_15",
    name: "Army Builder",
    desc: "Recruit 15 heroes.",
    icon: "🛡️",
    category: "collection",
    reward: { coins: 2500, stardust: 10 },
    condition: (stats) => stats.heroesRecruited >= 15,
  },
  {
    id: "ach_hero_30",
    name: "War Council",
    desc: "Recruit 30 heroes.",
    icon: "⚔️",
    category: "collection",
    reward: { coins: 5000, stardust: 20 },
    condition: (stats) => stats.heroesRecruited >= 30,
  },
  {
    id: "ach_hero_50",
    name: "Legendary Commander",
    desc: "Recruit 50 heroes.",
    icon: "🏳️",
    category: "collection",
    reward: { coins: 10000, stardust: 30 },
    condition: (stats) => stats.heroesRecruited >= 50,
  },
  {
    id: "ach_hero_100",
    name: "Hero Hoarder",
    desc: "Recruit 100 heroes.",
    icon: "🌟",
    category: "collection",
    reward: { coins: 25000, stardust: 50 },
    condition: (stats) => stats.heroesRecruited >= 100,
  },
  {
    id: "ach_items_5",
    name: "Loot Rookie",
    desc: "Find 5 items.",
    icon: "🎁",
    category: "collection",
    reward: { coins: 500, stardust: 3 },
    condition: (stats) => stats.itemsFound >= 5,
  },
  {
    id: "ach_items_10",
    name: "Treasure Hunter",
    desc: "Find 10 items.",
    icon: "🎒",
    category: "collection",
    reward: { coins: 1000, stardust: 5 },
    condition: (stats) => stats.itemsFound >= 10,
  },
  {
    id: "ach_items_25",
    name: "Collector",
    desc: "Find 25 items.",
    icon: "🏺",
    category: "collection",
    reward: { coins: 2500, stardust: 10 },
    condition: (stats) => stats.itemsFound >= 25,
  },
  {
    id: "ach_items_50",
    name: "Hoarder",
    desc: "Find 50 items.",
    icon: "📦",
    category: "collection",
    reward: { coins: 5000, stardust: 20 },
    condition: (stats) => stats.itemsFound >= 50,
  },
  {
    id: "ach_items_100",
    name: "Armory Master",
    desc: "Find 100 items.",
    icon: "🗄️",
    category: "collection",
    reward: { coins: 10000, stardust: 35 },
    condition: (stats) => stats.itemsFound >= 100,
  },

  // --- Prestige Achievements ---
  {
    id: "ach_prestige_1",
    name: "Void Rebirth",
    desc: "Perform your first Prestige.",
    icon: "♻️",
    category: "prestige",
    reward: { gems: 3, essence: 2 },
    condition: (stats, state) => (state?.prestigeCount || 0) >= 1,
  },
  {
    id: "ach_prestige_3",
    name: "Reborn Thrice",
    desc: "Perform 3 Prestiges.",
    icon: "🔄",
    category: "prestige",
    reward: { gems: 5, essence: 5 },
    condition: (stats, state) => (state?.prestigeCount || 0) >= 3,
  },
  {
    id: "ach_prestige_5",
    name: "Eternal Cycle",
    desc: "Perform 5 Prestiges.",
    icon: "🌀",
    category: "prestige",
    reward: { gems: 10, essence: 8 },
    condition: (stats, state) => (state?.prestigeCount || 0) >= 5,
  },
  {
    id: "ach_prestige_10",
    name: "Ascended Master",
    desc: "Perform 10 Prestiges.",
    icon: "🌙",
    category: "prestige",
    reward: { gems: 20, essence: 15 },
    condition: (stats, state) => (state?.prestigeCount || 0) >= 10,
  },

  // --- Bestiary Achievements ---
  {
    id: "ach_bestiary_5",
    name: "Monster Scholar",
    desc: "Discover 5 different enemies.",
    icon: "📖",
    category: "bestiary",
    reward: { coins: 1000, stardust: 5 },
    condition: (stats, state) => Object.keys(state?.bestiary || {}).length >= 5,
  },
  {
    id: "ach_bestiary_10",
    name: "Monster Expert",
    desc: "Discover 10 different enemies.",
    icon: "📚",
    category: "bestiary",
    reward: { coins: 2500, stardust: 10 },
    condition: (stats, state) => Object.keys(state?.bestiary || {}).length >= 10,
  },
  {
    id: "ach_bestiary_15",
    name: "Monster Professor",
    desc: "Discover 15 different enemies.",
    icon: "🎓",
    category: "bestiary",
    reward: { coins: 5000, stardust: 20 },
    condition: (stats, state) => Object.keys(state?.bestiary || {}).length >= 15,
  },
  {
    id: "ach_bestiary_20",
    name: "Monster Encyclopedia",
    desc: "Discover all 20 enemies!",
    icon: "🏆",
    category: "bestiary",
    reward: { coins: 10000, stardust: 35 },
    condition: (stats, state) => Object.keys(state?.bestiary || {}).length >= 20,
  },

  // --- Level Achievements ---
  {
    id: "ach_level_5",
    name: "Growing Stronger",
    desc: "Reach Profile Level 5.",
    icon: "📈",
    category: "level",
    reward: { coins: 1000, stardust: 5 },
    condition: (stats, state) => (state?.profile?.level || 1) >= 5,
  },
  {
    id: "ach_level_10",
    name: "Rising Star",
    desc: "Reach Profile Level 10.",
    icon: "⬆️",
    category: "level",
    reward: { coins: 2500, stardust: 10, gems: 1 },
    condition: (stats, state) => (state?.profile?.level || 1) >= 10,
  },
  {
    id: "ach_level_25",
    name: "Seasoned Hero",
    desc: "Reach Profile Level 25.",
    icon: "🌟",
    category: "level",
    reward: { coins: 5000, stardust: 20, gems: 3 },
    condition: (stats, state) => (state?.profile?.level || 1) >= 25,
  },
  {
    id: "ach_level_50",
    name: "Grand Champion",
    desc: "Reach Profile Level 50.",
    icon: "👑",
    category: "level",
    reward: { coins: 15000, stardust: 35, gems: 8 },
    condition: (stats, state) => (state?.profile?.level || 1) >= 50,
  },
  {
    id: "ach_level_100",
    name: "Midnight Legend",
    desc: "Reach Profile Level 100.",
    icon: "🌙",
    category: "level",
    reward: { coins: 50000, stardust: 50, gems: 15 },
    condition: (stats, state) => (state?.profile?.level || 1) >= 100,
  },

  // --- Time Achievements ---
  {
    id: "ach_time_10m",
    name: "Just Started",
    desc: "Play for 10 minutes.",
    icon: "⏱️",
    category: "time",
    reward: { coins: 500 },
    condition: (stats) => stats.totalPlayTimeMs >= 600000,
  },
  {
    id: "ach_time_1h",
    name: "Dedicated",
    desc: "Play for 1 hour total.",
    icon: "⏰",
    category: "time",
    reward: { coins: 2000 },
    condition: (stats) => stats.totalPlayTimeMs >= 3600000,
  },
  {
    id: "ach_time_10h",
    name: "Obsessed",
    desc: "Play for 10 hours total.",
    icon: "⌛",
    category: "time",
    reward: { coins: 10000 },
    condition: (stats) => stats.totalPlayTimeMs >= 36000000,
  },
  {
    id: "ach_time_24h",
    name: "Full Day Warrior",
    desc: "Play for 24 hours total.",
    icon: "📅",
    category: "time",
    reward: { coins: 25000 },
    condition: (stats) => stats.totalPlayTimeMs >= 86400000,
  },
  {
    id: "ach_time_100h",
    name: "No Life",
    desc: "Play for 100 hours total.",
    icon: "🕰️",
    category: "time",
    reward: { coins: 100000 },
    condition: (stats) => stats.totalPlayTimeMs >= 360000000,
  },
];
